version: '3'
services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: e-shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5431:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  spring-boot-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/e-shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345

volumes:
  postgres-data:
