create table customer
(
    customer_id integer generated by default as identity
        primary key,
    name        varchar(100) not null,
    surname     varchar(100) not null,
    email       varchar(100) not null unique ,
    password    varchar(500) not null,
    role        varchar(10)  not null
);

create table category
(
    category_id int generated by default as identity primary key,
    name        varchar(50) not null
);

create table category_parent_child
(
    parent_id integer not null
        references category,
    child_id  integer not null
        references category,
    primary key (parent_id, child_id)
);

create table product
(
    product_id  integer generated by default as identity
        primary key,
    name        varchar(100)     not null,
    price       double precision not null,
    amount      integer          not null,
    description varchar(1000)    not null,
    discount    integer          not null,
    category_id integer references category(category_id)
);


create table characteristic
(
    characteristic_id integer generated by default as identity
        primary key,
    name              varchar(100) not null ,
    is_range          boolean not null,
    from_             double precision,
    _to               double precision,
    category_id       integer
        references category
);

create table property(
                         property_id int generated by default as identity primary key ,
                         value varchar(50),
                         characteristic_id int references characteristic(characteristic_id)
);

create table product_attribute
(
    product_id   int references product (product_id),
    property_id int references property (property_id),
    primary key (product_id, property_id)
);

create table photo
(
    url        varchar(500) primary key,
    alt        varchar(200),
    product_id int references product (product_id)
);