create table if not exists customer
(
    customer_id integer generated by default as identity
        primary key,
    name        varchar(100) not null,
    surname     varchar(100) not null,
    email       varchar(100) not null unique,
    password    varchar(500) not null,
    role        varchar(10)  not null
);

create table if not exists category
(
    category_id int generated by default as identity primary key,
    name        varchar(50) not null,
    diverged    boolean     not null
);

create table if not exists category_parent_child
(
    parent_id integer not null
        references category on delete cascade,
    child_id  integer not null
        references category on delete cascade,
    primary key (parent_id, child_id)
);

create table if not exists product
(
    product_id  integer generated by default as identity
        primary key,
    name        varchar(100)     not null unique,
    price       double precision not null,
    amount      integer          not null,
    description varchar(1000)    not null,
    discount    integer          not null,
    category_id integer references category (category_id) on delete cascade,
    rating      double precision
);


create table if not exists characteristic
(
    characteristic_id integer generated by default as identity
        primary key,
    name              varchar(100)                                  not null,
    is_range          boolean                                       not null,
    from_             double precision,
    _to               double precision,
    category_id       integer references category on delete cascade not null
);

create table if not exists property
(
    property_id       int generated by default as identity primary key,
    value             varchar(50),
    characteristic_id int references characteristic (characteristic_id) on delete cascade
);

create table if not exists product_property
(
    product_id  int references product (product_id) on delete cascade,
    property_id int references property (property_id) on delete cascade,
    primary key (product_id, property_id)
);

create table if not exists comment
(
    comment_id  int generated by default as identity primary key,
    rating      smallint                                                not null,
    note        varchar(500),
    date_time   date                                                    not null,
    product_id  int references product (product_id) on delete cascade   not null,
    customer_id int references customer (customer_id) on delete cascade not null
);

create table if not exists photo
(
    url        varchar(500) primary key,
    product_id int references product (product_id) on delete cascade,
    comment_id int references comment (comment_id) on delete cascade
);

create table purchase
(
    purchase_id   int primary key generated by default as identity,
    purchase_date date,
    customer_id   int references customer
);

create table cart_item
(
    customer_id integer not null
        references customer on delete cascade,
    product_id  integer not null
        references product on delete cascade,
    total_count integer,
    purchase_id int references purchase,
    primary key (customer_id, product_id, purchase_id)
);

